library(benchmarkMetrics)
library(gitBasedProjects)
library(raster)
library(ncdf4)
library(rasterExtras)
library(rasterPlot)
library(mapdata)
library(plotrix)
library(MASS)
library(mapplots)
library(truncdist)
library(weights)

sourceAllLibs('src/')
sourceAllLibs('../benchmarkmetrics/benchmarkMetrics/')
source('cfg/params.r')
source('cfg/modelInfo.r')
