library(benchmarkMetrics)
source("../gitProjectExtras/gitBasedProjects/R/sourceAllLibs.r")
sourceAllLibs('../gitProjectExtras/gitBasedProjects/R/')

## uncomment on windows
#source('../gitProjectExtras/package_git2r.r')
#config(repository(), user.name="Douglas Kelley", user.email="douglas.i.kelley@gmail.com")
library(raster)
library(ncdf4)
library(rasterExtras)
library(rasterPlot)
library(mapdata)
library(plotrix)
library(MASS)
library(mapplots)
library(truncdist)

sourceAllLibs('src/')
sourceAllLibs('src/dataProcessing/')
sourceAllLibs('src/libs/')
sourceAllLibs('src/metrics/')
sourceAllLibs('src/plotting/')
sourceAllLibs('src/postProcessing/')
sourceAllLibs('src/processModelOutputs/')
sourceAllLibs('../benchmarkmetrics_github/benchmarkMetrics/')
sourceAllLibs('../benchmarkmetrics_github/benchmarkMetrics/R/')
sourceAllLibs('../rasterextrafuns/rasterPlotFunctions/R/')

source('cfg/params.r')
source('cfg/modelInfo.r')
