library(benchmarkMetrics)
source("../gitProjectExtras/gitBasedProjects/R/sourceAllLibs.r")
sourceAllLibs('../gitProjectExtras/gitBasedProjects/R/')

## uncomment on windows
source('../gitProjectExtras/package_git2r.r')
config(repository(), user.name="Douglas Kelley", user.email="douglas.i.kelley@gmail.com")
library(raster)
library(ncdf4)
library(rasterExtras)
library(rasterPlot)
library(mapdata)
library(plotrix)
library(MASS)
library(mapplots)
library(truncdist)

sourceAllLibs('src')
sourceAllLibs('../benchmarkmetrics/benchmarkMetrics/')
source('cfg/params.r')
source('cfg/modelInfo.r')