install.packages('devtools')
library(devtools)

install_github('douglask3/benchmarkmetrics/benchmarkMetrics')
install_bitbucket('douglask3/gitProjectExtras/gitBasedProjects')
install_bitbucket('douglask3/rasterExtraFuns/rasterExtras')
install_bitbucket('douglask3/rasterExtraFuns/rasterPlotFunctions')
install.packages('raster')
install.packages('mapdata')
install.packages('MASS')
